-- Create a test user first (since exercises require created_by)
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_token_new,
  email_change,
  email_change_sent_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '11111111-1111-1111-1111-111111111111',
  'authenticated',
  'authenticated',
  'test@example.com',
  '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', -- password: 'password'
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  '{"provider": "email", "providers": ["email"]}',
  '{}',
  false,
  NOW(),
  NOW(),
  null,
  null,
  '',
  '',
  null,
  '',
  '',
  null,
  '',
  0,
  null,
  '',
  null,
  false,
  null
) ON CONFLICT (id) DO NOTHING;

-- Create a profile for the user
INSERT INTO public.profiles (
  id,
  first_name,
  last_name,
  role,
  created_at,
  updated_at
) VALUES (
  '11111111-1111-1111-1111-111111111111',
  'Test',
  'User',
  'trainer',
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;

-- Insert sample video exercise
INSERT INTO public.exercises (
  id,
  title,
  description,
  course_name,
  difficulty,
  due_date,
  points,
  estimated_time,
  status,
  created_by,
  form_structure,
  exercise_type,
  content_url,
  auto_grade,
  days_to_open,
  days_to_due,
  created_at
) VALUES (
  '3f876434-e21d-46ef-ba18-924da0c4754c',
  'تمرین ویدیویی نمونه',
  'این یک تمرین ویدیویی برای تست عملکرد است',
  'دوره نمونه',
  'beginner',
  (NOW() + INTERVAL '7 days')::DATE,
  10,
  '30 دقیقه',
  'active',
  '11111111-1111-1111-1111-111111111111',
  '{"questions": []}',
  'video',
  'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
  false,
  0,
  7,
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  exercise_type = EXCLUDED.exercise_type,
  content_url = EXCLUDED.content_url,
  auto_grade = EXCLUDED.auto_grade;

-- Insert sample audio exercise
INSERT INTO public.exercises (
  id,
  title,
  description,
  course_name,
  difficulty,
  due_date,
  points,
  estimated_time,
  status,
  created_by,
  form_structure,
  exercise_type,
  content_url,
  auto_grade,
  days_to_open,
  days_to_due,
  created_at
) VALUES (
  '22222222-2222-2222-2222-222222222222',
  'تمرین صوتی نمونه',
  'این یک تمرین صوتی برای تست عملکرد است',
  'دوره نمونه',
  'beginner',
  (NOW() + INTERVAL '7 days')::DATE,
  10,
  '15 دقیقه',
  'active',
  '11111111-1111-1111-1111-111111111111',
  '{"questions": []}',
  'audio',
  'https://www.soundjay.com/misc/sounds/bell-ringing-05.wav',
  false,
  0,
  7,
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  exercise_type = EXCLUDED.exercise_type,
  content_url = EXCLUDED.content_url,
  auto_grade = EXCLUDED.auto_grade;

-- Insert sample simple exercise
INSERT INTO public.exercises (
  id,
  title,
  description,
  course_name,
  difficulty,
  due_date,
  points,
  estimated_time,
  status,
  created_by,
  form_structure,
  exercise_type,
  content_url,
  auto_grade,
  days_to_open,
  days_to_due,
  created_at
) VALUES (
  '33333333-3333-3333-3333-333333333333',
  'تمرین ساده نمونه',
  'این یک تمرین ساده برای تست عملکرد است',
  'دوره نمونه',
  'beginner',
  (NOW() + INTERVAL '7 days')::DATE,
  5,
  '10 دقیقه',
  'active',
  '11111111-1111-1111-1111-111111111111',
  '{"questions": []}',
  'simple',
  null,
  true,
  0,
  7,
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  exercise_type = EXCLUDED.exercise_type,
  content_url = EXCLUDED.content_url,
  auto_grade = EXCLUDED.auto_grade;
