// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dynmgviifqrozsczabvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5bm1ndmlpZnFyb3pzY3phYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzEyOTEsImV4cCI6MjA2NTUwNzI5MX0.EV48lv2en32BeYOTr4eroy2V6D0KScgi1c5ng8DZb5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);